"""Add image and notes

Revision ID: ac42cb221a47
Revises: bcaf93556e67
Create Date: 2026-01-04 10:14:26.610142

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac42cb221a47'
down_revision = 'bcaf93556e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image_url')
    op.drop_column('rooms', 'description')
    op.drop_column('reservations', 'notes')
    # ### end Alembic commands ###